### ISSUE TITLE
Resource no longer runs on the server this has started happening within 24 hours

### ISSUE THREAD

**Issue by ParaPup** [citizenfx/screenshot-basic#25]
https://media.discordapp.net/attachments/545408420493393920/712480544977453096/unknown.png?width=919&height=575

**Comment by ParaPup** [comment]
![unknown (3)](https://user-images.githubusercontent.com/2827347/82396074-66ddc700-9a90-11ea-8af1-5a674d82ffab.png)

**Comment by ParaPup** [comment]
It randomly without touching it at all resolved itself, however, all screenshots are now black since.

**Comment by CruelAlpha** [comment]
This is due to an Nvidia update I believe, waiting on a fix.

**Comment by ParaPup** [comment]
You reckon? and not to do with FiveM changing calls to the graphics card? https://github.com/citizenfx/fivem/commit/f3698391f17aeffd156f3aa06e71024b8c572d09 https://github.com/citizenfx/fivem/commit/b4623eb22692f7c6111077dba7abbde4e96c524f https://github.com/citizenfx/fivem/commit/e0ee8df99f6a72d688f80b409b8f3e979be8e72a https://github.com/citizenfx/fivem/commit/c936da7c3cd1d508425ea7a3c7ef11bc3defb3b7 https://github.com/citizenfx/fivem/commit/cf5386301e406d290523d5f732a45e009aba2b5e
