### ISSUE TITLE
Black screenshot

### ISSUE THREAD

**Issue by jonassvensson4** [citizenfx/screenshot-basic#5]
When using the exports it just returns a black screenshot.

What I've tried:
* Tried all of the exports
* Re-installed the resource twice
* Installed a completely new server to test it on
* Tried it in every window mode (fullscreen, windowed, windowed borderless)
* No errors, it successfully uploads the screenshot to w.wew.wtf OR saves the screenshot locally but it's just all black

Have someone found a solution for this?

**Comment by shadowoffice** [comment]
Same here

**Comment by jonassvensson4** [comment]
I didn't do anything but apparently it started to work.

**Comment by jonassvensson4** [comment]
I did run in to this issue again. It seems a bit weird. 

I'm not even sure if this is how I solved it but if you run in to this problem try this:
- Clear the server cache, specifically the screenshot-basic
- Run your server as an administrator 
- Restart your server when it has started all the resource etc and run it once again as administrator

**Comment by hemato** [comment]
can you guys help me i have same issue

**Comment by insayd10** [comment]
its happening with cache

**Comment by hemato** [comment]
> its happening with cache

what is that mean ?

**Comment by insayd10** [comment]
> > its happening with cache
> 
> what is that mean ?

cache gives always same link for upload

**Comment by hemato** [comment]
so how we can fix it ?

**Comment by hemato** [comment]
> > > its happening with cache
> > 
> > 
> > what is that mean ?
> 
> cache gives always same link for upload

so how we can fix it ?
