### ISSUE TITLE
Hi guys, Madiran inform

### ISSUE THREAD

**Issue by insayd10** [citizenfx/screenshot-basic#9]
I've had a lot of problems about this resource, I've listened to those who have problems.
I'm starting this issue to help you,

Firstly the source not compatible with linux ( no distribution ) 
The second is a wrong solution in my opinion, consuming too much resources and coming with bugs. 

I'm taking over this project, and I'm gonna come up with a better solution. Goodnight

**Comment by berdancanyet** [comment]
Glad to hear.

**Comment by mrrpstaff** [comment]
Any progress?

**Comment by insayd10** [comment]
yes i ill share
